package sudoku;

import sudoku.core.Solution;
import sudoku.core.drools.DroolsField;

global Solution solution;

rule "Contradiction"
salience 100
when
	$field1 : DroolsField(value != null)
	$field2 : DroolsField(this != $field1, value == $field1.value,
		rowIndex == $field1.rowIndex || columnIndex == $field1.columnIndex || blockIndex == $field1.blockIndex)
then
	solution.setResultStatus(Solution.ResultStatus.CONTRADICTION);
end

rule "Table solved"
salience 100
when
	not DroolsField(value == null)
then
	solution.setResultStatus(Solution.ResultStatus.SOLVED);
end
